[build]
    publish = 'build'


[[redirects]]
    from = '/test'
    to = 'https://video-search-api.onrender.com/users/admin'
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/users/login'
    to = 'https://video-search-api.onrender.com/users/login'
    status = 302
    headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}


[[redirects]]
    from = '/users/register'
    to = 'https://video-search-api.onrender.com/users/register'
    status = 302
    force = false
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/users/verify-token'
    to = 'https://video-search-api.onrender.com/users/verify-token'
    status = 302
    force = true
    headers = {X-From = "Netlify"}


[[redirects]]
    from = '/api'
    to = 'https://video-search-api.onrender.com/api/'
    status = 302
    force = true
    headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}

[[redirects]]
    from = '/api/*'
    to = 'https://video-search-api.onrender.com/api/:splat'
    status = 200
    